# L9_META
#   l9_schema: 1
#   repo: Quantum-L9/l9-graphiti-memory
#   path: tests/integration/test_topology_publication_e2e_v2.py
#   layer: test
#   owner: memory-control-plane
#   status: active
#   version: 2.2.0
#   updated: 2026-08-30

"""The same end-to-end qualification, under the current lowering contract.

``test_topology_publication_e2e`` qualifies ``lowering/v1``. The producer has
since moved to ``lowering/v2``, which carries an edge's direction and properties
into the intent as structured data rather than only inside the human ``content``
string — a different durable write for the same fact, keyed differently on
purpose. This repository declares support for both in
``SUPPORTED_LOWERING_CONTRACTS``.

Regenerating the v1 fixture in place would have swapped which of the two is
qualified, leaving a version this repository claims to accept exercised by
nothing. So this is a second fixture and a second suite, and both stay for as
long as both versions are declared supported.

What is asserted here is not "v2 works" in general. It is that the *same* corpus,
lowered under the newer contract, still admits exactly once, still replays as a
duplicate rather than a second write, and still binds every record to the packet
it came from — the properties that must not move when the contract does.

The fixtures were generated by the producer's own compiler and plan builder at a
recorded revision (see PROVENANCE.md there). No network effect exists in any
stage: canonical writes land in a temporary SQLite store behind a null
projection.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from l9_graphite_memory.adapters import NullProjection, SQLiteRecordStore
from l9_graphite_memory.contracts import MemoryPrincipal
from l9_graphite_memory.ingestion import (
    execute_topology_publication,
    load_publication_plan,
    load_verified_bundle,
)
from l9_graphite_memory.ingestion.publication_identity import SUPPORTED_LOWERING_CONTRACTS
from l9_graphite_memory.services import MemoryService

FIXTURE_ROOT = Path(__file__).resolve().parents[1] / "fixtures" / "topology_publication_v2"
NAMESPACES = (
    "l9.constellation/l9-gate-sdk",
    "l9.constellation/l9-mcp-server",
    "l9.constellation/l9-assertion-sample",
    "l9.constellation/unscoped",
)


@pytest.fixture(scope="module")
def plan():
    return load_publication_plan(load_verified_bundle(FIXTURE_ROOT / "plan-bundle"))


@pytest.fixture(scope="module")
def topology_bundle():
    return load_verified_bundle(FIXTURE_ROOT / "topology-bundle")


@pytest.fixture
def principal() -> MemoryPrincipal:
    return MemoryPrincipal(
        principal_id="topology-operator",
        tenant_id="tenant-constellation",
        read_namespaces=NAMESPACES,
        write_namespaces=NAMESPACES,
    )


@pytest.fixture
def service(tmp_path: Path) -> MemoryService:
    built = MemoryService(SQLiteRecordStore(tmp_path / "canonical.sqlite3"), NullProjection())
    built.initialize()
    return built


def test_the_fixture_is_the_contract_version_this_suite_is_for(plan) -> None:
    """Otherwise a regenerated fixture could silently make this a copy of v1."""
    versions = {
        candidate.memory_intent.request.metadata.get("lowering_contract_version")
        for candidate in plan.candidates
    }
    assert versions == {"lowering/v2"}
    assert "lowering/v2" in SUPPORTED_LOWERING_CONTRACTS
    assert "lowering/v1" in SUPPORTED_LOWERING_CONTRACTS


def test_stage_1_exact_producer_plan_validates(plan) -> None:
    assert plan.plan_version == "1.0.0"
    assert plan.producer.name == "l9-constellation-topology/publication"
    kinds = {candidate.candidate_kind for candidate in plan.candidates}
    assert kinds == {"entity", "relationship", "claim"}
    eligible = [c for c in plan.candidates if c.eligibility.status == "eligible"]
    held = [c for c in plan.candidates if c.eligibility.status == "held"]
    assert len(eligible) == 73
    assert len(held) == 3


def test_stage_2_preflight_commits_nothing(plan, topology_bundle, principal, service) -> None:
    receipt = execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="preflight",
    )
    assert receipt.attempted_count == 73
    assert receipt.admitted_count == 73
    assert service.store.stats()["records"] == 0
    assert all(r.memory_record_id is None for r in receipt.candidate_results)


def test_stages_3_to_5_apply_replay_and_canonical_readback(
    plan, topology_bundle, principal, service
) -> None:
    applied = execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="apply",
    )
    assert applied.attempted_count == applied.eligible_count == 73
    assert applied.admitted_count == 73
    assert applied.failed_count == 0
    assert service.store.stats()["records"] == 73

    replayed = execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="apply",
    )
    assert replayed.admitted_count == 0
    assert replayed.duplicate_count == 73
    assert service.store.stats()["records"] == 73

    first_ids = {
        r.candidate_id: r.memory_record_id for r in applied.candidate_results if r.memory_record_id
    }
    replay_ids = {
        r.candidate_id: r.memory_record_id for r in replayed.candidate_results if r.memory_record_id
    }
    assert first_ids == replay_ids

    keys_by_candidate = {c.candidate_id: c.idempotency_key for c in plan.candidates}
    for result in applied.candidate_results:
        if not result.attempted:
            continue
        record = service.get(principal, result.memory_record_id)
        assert record is not None
        assert record.idempotency_key == keys_by_candidate[result.candidate_id]
        metadata = record.metadata
        assert metadata["topology_packet_id"] == plan.source_topology_packet.packet_id
        assert metadata["topology_semantic_hash"] == plan.source_topology_semantic_hash
        assert metadata["publication_candidate_id"] == result.candidate_id


def test_the_richer_contract_reaches_the_stored_record(
    plan, topology_bundle, principal, service
) -> None:
    """What v2 added must survive admission, or the version bump bought nothing.

    An edge's direction and properties are the whole reason the contract moved.
    Asserted on the record read back out of the store rather than on the plan,
    because the plan carrying them and the store keeping them are two claims.
    """
    execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="apply",
    )
    relations = []
    for candidate in plan.candidates:
        relation = candidate.memory_intent.request.metadata.get("topology_relation")
        if relation is not None:
            relations.append((candidate.candidate_id, relation))
    assert relations, "the fixture published no relationship candidate"

    for _, relation in relations:
        assert relation["direction"] in {"outbound", "inbound", "bidirectional"}
        assert relation["edge_type"]
        assert relation["source_id"] and relation["target_id"]
        assert "properties" in relation


def test_the_two_contract_versions_key_different_writes(plan) -> None:
    """v1 and v2 of the same fact are two durable writes, deliberately.

    A fact lowered under v2 states more than the same fact under v1. Keying the
    richer write as a retry of the poorer one would make the store answer
    DUPLICATE and drop the added structure — which is exactly what the contract
    version in the key exists to prevent.
    """
    v1_plan = load_publication_plan(
        load_verified_bundle(
            Path(__file__).resolve().parents[1] / "fixtures/topology_publication/plan-bundle"
        )
    )
    v1_keys = {c.candidate_id: c.idempotency_key for c in v1_plan.candidates}
    v2_keys = {c.candidate_id: c.idempotency_key for c in plan.candidates}

    shared = set(v1_keys) & set(v2_keys)
    assert shared, "the two fixtures share no candidate, so they compare nothing"
    # The candidate id is the logical fact and does not move; the idempotency
    # key is the exact durable admission and must.
    assert all(v1_keys[candidate] != v2_keys[candidate] for candidate in shared)
