# L9_META
#   l9_schema: 1
#   repo: Quantum-L9/l9-graphiti-memory
#   path: tests/integration/test_topology_publication_e2e.py
#   layer: test
#   owner: memory-control-plane
#   status: active
#   version: 2.2.0
#   updated: 2026-08-23

"""Canonical E2E qualification against the exact bound Topology plan.

The fixture bundles under ``tests/fixtures/topology_publication`` were
generated by the producer's own compiler and plan builder at the bound
l9-constellation-topology PR #18 head (see PROVENANCE.md there). No network
effect exists anywhere in these stages: canonical writes land in a temporary
SQLite store behind a null projection, and Gate is consulted only through its
static intent validator.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from l9_graphite_memory.adapters import NullProjection, SQLiteRecordStore
from l9_graphite_memory.contracts import MemoryPrincipal
from l9_graphite_memory.ingestion import (
    execute_topology_publication,
    load_publication_plan,
    load_verified_bundle,
)
from l9_graphite_memory.services import MemoryService

FIXTURE_ROOT = Path(__file__).resolve().parents[1] / "fixtures" / "topology_publication"
NAMESPACES = (
    "l9.constellation/l9-gate-sdk",
    "l9.constellation/l9-mcp-server",
    "l9.constellation/l9-assertion-sample",
    "l9.constellation/unscoped",
)


@pytest.fixture(scope="module")
def plan():
    return load_publication_plan(load_verified_bundle(FIXTURE_ROOT / "plan-bundle"))


@pytest.fixture(scope="module")
def topology_bundle():
    return load_verified_bundle(FIXTURE_ROOT / "topology-bundle")


@pytest.fixture
def principal() -> MemoryPrincipal:
    return MemoryPrincipal(
        principal_id="topology-operator",
        tenant_id="tenant-constellation",
        read_namespaces=NAMESPACES,
        write_namespaces=NAMESPACES,
    )


@pytest.fixture
def service(tmp_path: Path) -> MemoryService:
    built = MemoryService(SQLiteRecordStore(tmp_path / "canonical.sqlite3"), NullProjection())
    built.initialize()
    return built


def test_stage_1_exact_producer_plan_validates(plan) -> None:
    assert plan.plan_version == "1.0.0"
    assert plan.producer.name == "l9-constellation-topology/publication"
    kinds = {candidate.candidate_kind for candidate in plan.candidates}
    assert kinds == {"entity", "relationship", "claim"}
    eligible = [c for c in plan.candidates if c.eligibility.status == "eligible"]
    held = [c for c in plan.candidates if c.eligibility.status == "held"]
    assert len(eligible) == 73
    assert len(held) == 3
    assert len(plan.skipped_candidates) == 40
    predicates = {
        c.memory_intent.request.assertion.predicate
        for c in eligible
        if c.memory_intent.request.assertion is not None
    }
    assert "DEPENDS_ON" in predicates
    held_reasons = {reason for c in held for reason in c.eligibility.reasons}
    assert "conflict.unresolved_material" in held_reasons


def test_stage_2_preflight_commits_nothing(plan, topology_bundle, principal, service) -> None:
    receipt = execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="preflight",
    )
    assert receipt.attempted_count == 73
    assert receipt.admitted_count == 73
    assert service.store.stats()["records"] == 0
    assert all(r.memory_record_id is None for r in receipt.candidate_results)


def test_stages_3_to_5_apply_replay_and_canonical_readback(
    plan, topology_bundle, principal, service
) -> None:
    applied = execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="apply",
    )
    assert applied.attempted_count == applied.eligible_count == 73
    assert applied.admitted_count == 73
    assert applied.failed_count == 0
    assert service.store.stats()["records"] == 73

    replayed = execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="apply",
    )
    assert replayed.admitted_count == 0
    assert replayed.duplicate_count == 73
    assert service.store.stats()["records"] == 73
    first_ids = {
        r.candidate_id: r.memory_record_id for r in applied.candidate_results if r.memory_record_id
    }
    replay_ids = {
        r.candidate_id: r.memory_record_id for r in replayed.candidate_results if r.memory_record_id
    }
    assert first_ids == replay_ids

    keys_by_candidate = {c.candidate_id: c.idempotency_key for c in plan.candidates}
    for result in applied.candidate_results:
        if not result.attempted:
            continue
        record = service.get(principal, result.memory_record_id)
        assert record is not None
        assert record.idempotency_key == keys_by_candidate[result.candidate_id]
        metadata = record.metadata
        assert metadata["topology_packet_id"] == plan.source_topology_packet.packet_id
        assert metadata["topology_semantic_hash"] == plan.source_topology_semantic_hash
        assert metadata["publication_candidate_id"] == result.candidate_id


def test_canonical_records_come_only_from_eligible_candidates(
    plan, topology_bundle, principal, service
) -> None:
    execute_topology_publication(
        plan=plan,
        topology_bundle=topology_bundle,
        principal=principal,
        memory_service=service,
        mode="apply",
    )
    held_or_rejected_keys = {
        c.idempotency_key for c in plan.candidates if c.eligibility.status != "eligible"
    }
    for namespace in NAMESPACES:
        for record in service.store.list_records(principal.tenant_id, namespace):
            assert record.idempotency_key not in held_or_rejected_keys


def test_effect_identity_unrelated_candidates_do_not_rekey(plan) -> None:
    """Two candidates never share an idempotency key, and each key is v3-scoped.

    Adding an unrelated fact upstream produces a new candidate with its own
    key; existing keys are content-derived, so unaffected facts keep both key
    and record id — proven for the replay case in the stages test above.
    """
    keys = [c.idempotency_key for c in plan.candidates]
    assert len(keys) == len(set(keys))
    assert all(key.startswith("l9-topology-publication/v3:") for key in keys)


def test_current_topology_plan_does_not_yet_emit_source_locator(plan) -> None:
    """WS12 status pin: CURRENT_TOPOLOGY_LOCATOR_LOWERING_NOT_YET_PRESENT.

    The bound producer revision does not lower structured source locators yet.
    Memory's contract is ready for the producer revision that does; nothing is
    invented here from prose. When this test starts failing because a locator
    appeared, wire the conformance assertions from
    tests/unit/topology_publication/test_locator_future_conformance.py into
    this E2E instead of deleting the expectation.
    """
    for candidate in plan.candidates:
        request = candidate.memory_intent.request
        assert request.provenance.source_locator is None
        assert all(item.source_locator is None for item in request.evidence)
