# L9_META
#   l9_schema: 1
#   repo: Quantum-L9/l9-graphiti-memory
#   path: tests/unit/topology_publication/test_identity_golden_vectors.py
#   layer: test
#   owner: memory-control-plane
#   status: active
#   version: 2.2.0
#   updated: 2026-08-29

"""The consumer's identity algorithm must equal the producer's, vector for vector.

``publication_identity`` reimplements the producer's canonicalization because
this package does not depend on ``l9-constellation-topology`` and must not: a
consumer that validated a producer's claim with the producer's own code would
prove only that the code is self-consistent.

What holds the two implementations together is this file. The vectors are
generated by the producer's own ``publication.identity`` module at a recorded
revision and asserted here; the producer repository asserts the same file. A
divergence in either canonicalization — key ordering, float formatting, unicode
escaping, the volatile-field set, evidence sort order — breaks these vectors
before it can break a real plan.

Regenerate only from the producer, never by pasting this implementation's own
output: a vector produced by the side under test proves nothing.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from l9_graphite_memory.ingestion.publication_identity import (
    SUPPORTED_IDEMPOTENCY_ALGORITHMS,
    SUPPORTED_LOWERING_CONTRACTS,
    candidate_id,
    candidate_identity,
    confidence_semantics,
    evidence_semantics,
    idempotency_key,
)

VECTOR_FILE = (
    Path(__file__).resolve().parents[2]
    / "fixtures"
    / "publication_identity"
    / "golden-vectors.json"
)


def _document() -> dict[str, Any]:
    return json.loads(VECTOR_FILE.read_text(encoding="utf-8"))


def _vectors() -> list[dict[str, Any]]:
    return _document()["vectors"]


def _identity(vector: dict[str, Any]) -> dict[str, Any]:
    spec = vector["identity"]
    return candidate_identity(
        operation=spec["operation"],
        candidate_kind=spec["candidate_kind"],
        namespace=spec["namespace"],
        memory_class=spec["memory_class"],
        content=spec["content"],
        assertion=spec["assertion"],
        source_topology_entity_ids=tuple(spec["source_topology_entity_ids"]),
    )


def test_vector_file_is_bound_to_a_producer_revision() -> None:
    """A vector set that cannot name where it came from proves nothing."""
    document = _document()
    origin = document["generated_from"]
    assert origin["producer_repository"] == "Quantum-L9/l9-constellation-topology"
    assert len(origin["producer_revision"]) == 40
    assert document["effect_identity_algorithm_version"] in SUPPORTED_IDEMPOTENCY_ALGORITHMS
    assert document["lowering_contract_version"] in SUPPORTED_LOWERING_CONTRACTS
    assert len(document["vectors"]) >= 4


@pytest.mark.parametrize("vector", _vectors(), ids=lambda item: item["label"])
def test_candidate_id_matches_the_producer(vector: dict[str, Any]) -> None:
    assert candidate_id(_identity(vector)) == vector["expected_candidate_id"]


@pytest.mark.parametrize("vector", _vectors(), ids=lambda item: item["label"])
def test_idempotency_key_matches_the_producer(vector: dict[str, Any]) -> None:
    document = _document()
    recomputed = idempotency_key(
        _identity(vector),
        algorithm_version=document["effect_identity_algorithm_version"],
        lowering_contract_version=document["lowering_contract_version"],
        local_evidence=tuple(
            evidence_semantics(
                evidence_kind=item["evidence_kind"],
                source_content_digest=item["source_content_digest"],
                stable_source_locator=item["stable_source_locator"],
            )
            for item in vector["local_evidence"]
        ),
        confidence=confidence_semantics(**vector["confidence"]),
        derivation_kind=vector["derivation_kind"],
    )
    assert recomputed == vector["expected_idempotency_key"]


def test_evidence_order_does_not_change_the_key() -> None:
    """Two writes supported by the same evidence are one write.

    The producer sorts evidence semantics before hashing, so a key that moved
    with resolution order would make a re-publication of an unchanged fact look
    like a new durable operation.
    """
    document = _document()
    vector = next(item for item in _vectors() if len(item["local_evidence"]) > 1)
    semantics = [
        evidence_semantics(
            evidence_kind=item["evidence_kind"],
            source_content_digest=item["source_content_digest"],
            stable_source_locator=item["stable_source_locator"],
        )
        for item in vector["local_evidence"]
    ]
    keys = {
        idempotency_key(
            _identity(vector),
            algorithm_version=document["effect_identity_algorithm_version"],
            lowering_contract_version=document["lowering_contract_version"],
            local_evidence=tuple(order),
            confidence=confidence_semantics(**vector["confidence"]),
            derivation_kind=vector["derivation_kind"],
        )
        for order in (semantics, list(reversed(semantics)))
    }
    assert keys == {vector["expected_idempotency_key"]}


def test_a_changed_claim_changes_the_key() -> None:
    """The key must move when the requested durable operation differs."""
    document = _document()
    vector = _vectors()[0]

    def key_for(confidence: dict[str, Any]) -> str:
        return idempotency_key(
            _identity(vector),
            algorithm_version=document["effect_identity_algorithm_version"],
            lowering_contract_version=document["lowering_contract_version"],
            local_evidence=(),
            confidence=confidence_semantics(**confidence),
            derivation_kind=vector["derivation_kind"],
        )

    baseline = dict(vector["confidence"])
    stronger = {**baseline, "score": baseline["score"] + 0.05}
    assert key_for(baseline) != key_for(stronger)
